let map_token = function
  | VBParser.TRUE (_, s)
  | VBParser.FALSE (_, s)
  | VBParser.SUB (_, s)
  | VBParser.IF (_, s)
  | VBParser.ELSE (_, s)
  | VBParser.WHILE (_, s)
  | VBParser.ENDSUB (_, s)
  | VBParser.ENDIF (_, s)
  | VBParser.ENDWHILE (_, s)
  | VBParser.ELSEIF (_, s)
  | VBParser.AND (_, s)
  | VBParser.OR (_, s)
  | VBParser.NOT (_, s)
  | VBParser.EQ (_, s)
  | VBParser.NEW (_, s)
  | VBParser.DOT (_, s)
  | VBParser.LEFT (_, s)
  | VBParser.RIGHT (_, s)
  | VBParser.AHEAD (_, s)
  | VBParser.HERE (_, s)
  | VBParser.NORTH (_, s)
  | VBParser.SOUTH (_, s)
  | VBParser.EAST (_, s)
  | VBParser.WEST (_, s)
  | VBParser.LPAREN (_, s)
  | VBParser.RPAREN (_, s)
  | VBParser.COMMA (_, s)
  | VBParser.THEN (_, s)
  | VBParser.DIM (_, s)
  | VBParser.AS (_, s)
  | VBParser.ID (s, _) -> s
  | VBParser.INT (n, _) -> string_of_int n
  | VBParser.NEWLINE _ -> "Newline"
  | VBParser.EOF -> "EOF"
