image: docker:latest

stages:
  - build-ocaml
  - build-angular
  - test-angular

build-ocaml:
  image: ocaml/opam2:alpine-3.9-ocaml-4.07
  stage: build-ocaml
  artifacts:
    paths:
      - src/compiler/_build/
  script:
    - sudo apk update
    - sudo apk add m4
    - opam update
    - opam install -y dune menhir js_of_ocaml-compiler js_of_ocaml-ppx js_of_ocaml ounit
    - cd src/compiler
    - dune runtest
    - dune build ./JerooCompiler.bc.js --profile release

build-angular:
  image: node:8.15-alpine
  stage: build-angular
  artifacts:
    paths:
      - dist/
      - node_modules/
  script:
    - yarn install
    - yarn lint
    - yarn build --prod

test-angular:
  image: timbru31/node-chrome:alpine
  stage: test-angular
  script:
    - google-chrome-stable --version
    - export CHROME_BIN=google-chrome-stable
    - yarn install
    - yarn test
    - yarn e2e
