image: docker:latest

stages:
  - build-ocaml
  - build-angular

build-ocaml:
  image: opam2:alpine-3.9-ocaml-4.07
  stage: build-ocaml
  artifacts:
    paths:
      - src/compiler/_build/
  script:
    - opam install -y dune menhir js_of_ocaml-compiler js_of_ocaml-ppx js_of_ocaml ounit
    - cd src/compiler
    - dune runtest
    - dune build ./JerooCompiler.bc.js --profile release

build-angular:
  image: node:8.15-alpine
  stage: build-angular
  artifacts:
    paths:
      - dist/
  script:
    - yarn install
    - yarn build --prod
